console.log(fruits.toString())
// console.log(fruits.join("|"))
// console.log(fruits.pop())
// console.log(fruits.push("Grapes"))
// console.log(fruits.shift())
// console.log(fruits.unshift())
// console.log(fruits.concat(["Kiwi", "Blackberry"]))
// console.log(fruits.splice(0))
// console.log(fruits.slice(1))